apiVersion: apps/v1
kind: Deployment
metadata:
  name: canteen-server
  namespace: "{{ .Values.tumid }}-devops25"
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app: canteen-server-selector
  template:
    metadata:
      labels:
        app: canteen-server-selector
    spec:
      containers:
        - name: server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: {{ .Values.server.service.targetPort }}
          env:
            {{- range .Values.server.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
