# This file contains the default values for the Canteen App Helm chart.

# Add your tumid here
tumid:

##################################################################################################################
# No changes needed below this line
namespace:
  create: false

server:
  image:
    repository: ghcr.io/aet-devops25/w05-template/server
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  replicaCount: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker

client:
  image:
    repository: ghcr.io/aet-devops25/w05-template/client
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  replicaCount: 1

ingress:
  enabled: true
  className: "nginx"
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
